global proc zenMapUnmappedFaces(string $faces[])
{
	string	$sel[]=`ls -sl`;

	string	$obj=zenReturnFirstStringItem(`ls -o $faces`);
		
	// get unmapped faces
		select $faces;
		polySelectConstraint -m 3 -t 8 -tx 2;
	string 	$unmappedFaces[] = `ls -sl`;
		polySelectConstraint -dis;	
	
	// make UVs
		if(size($unmappedFaces))
		{
			delete -ch $obj;
			polyForceUV -unitize $unmappedFaces;
			polyLayoutUV $unmappedFaces;
			delete -ch $obj;
		}
		
	
		select $sel;
}
